### ISSUE TITLE
GlobalItem.PreOpenVanillaBag does not prevent consuming bag items, nor does it indicate which inventory item is being opened

### ISSUE THREAD

**Issue by hamstar0** [blushiemagic/tModLoader#372] opened 2018-07-01 15:56 UTC
### Description

See title.

### Steps to Reproduce

See title.

### Expected behavior 

See title.

### Actual behavior

See title.

### Reproduction frequency

Always

### Versions

v0.10.1.4

### Mods

Any.

**Comment by Jofairden** [comment] 2018-07-09 11:23
I'm not sure, what do you mean @hamstar0 ? It should prevent if you return false, and it indicates which item it is by the context and arg parameters.

**Comment by Chicken-Bones** [comment] 2018-07-09 13:33
I believe he might be referring to the lack of a 'slot' in Terraria, so if you have multiple of the same item in your inventory you don't know which one was clicked.

**Comment by hamstar0** [comment] 2018-07-09 18:07
Exactly. Even a direct `Item` reference (as opposed to an inventory index) would give me something to work with...

Also,, again, the bag is consumed no matter whether one returns true or false.

**Comment by JavidPack** [comment] 2018-07-09 18:17
K, but the documentation says "Return false to stop the default items from being dropped; returns true by default. ". I don't think preventing consumption is intended for this hook. With 0.10.1.5, I believe ConsumeItem will be properly hooked up to the items and happens before PreOpenVanillaBag. Does that solve your intended use?

**Comment by DarkLight66** [comment] 2018-07-09 19:29
Actually, this was implemented in 0.10.1.4, so you can use ConsumeItem for that already.

**Comment by hamstar0** [comment] 2018-07-09 23:38
I seem to have complications using it for bags.

**Comment by JavidPack** [comment] 2018-07-10 00:53
K, post a minimal reproducible example and we can see.

**Comment by hamstar0** [comment] 2018-07-10 03:50
`using System.Collections.Generic;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;


namespace ConsumeItemBagFail {
	class ConsumeItemBagFailMod : Mod {
		public ConsumeItemBagFailMod() {
			this.Properties = new ModProperties() {
				Autoload = true,
				AutoloadGores = true,
				AutoloadSounds = true
			};
		}
	}


	class ConsumeItemBagFailItem : GlobalItem {
		public override bool ConsumeItem( Item item, Player player ) {
			if( item.Name == "Treasure Bag" ) {
				Main.NewText( "No soup for you!" );
				return false;
			}
			return base.ConsumeItem( item, player );
		}
	}


	class ConsumeItemBagFailPlayer : ModPlayer {
		public override void SetupStartInventory( IList<Item> items ) {
			var bag1 = new Item();
			var bag2 = new Item();
			bag1.SetDefaults( ItemID.CultistBossBag );
			bag2.SetDefaults( ItemID.EyeOfCthulhuBossBag );

			items.Add( bag1 );
			items.Add( bag2 );
		}
	}
}
`

**Comment by JavidPack** [comment] 2018-07-10 04:15
```cs
		public override bool ConsumeItem(Item item, Player player)
		{
			if (item.Name == "Treasure Bag")
			{
				// Main.NewText("No soup for you!");
				return false;
			}
			return base.ConsumeItem(item, player);
		}

		public override bool PreOpenVanillaBag(string context, Player player, int arg)
		{
			if (context == "bossBag")
			{
				Main.NewText("No soup for you!");
				return false;
			}
			return base.PreOpenVanillaBag(context, player, arg);
		}
```

Works for me.

**Comment by hamstar0** [comment] 2018-07-10 06:39
Other than knowing which bag opens (I guess doable by communicating between ConsumeItem and PreOpenVanillaBag), that works, and is in fact what I've been using in Nihilism mod as my solution.

**Comment by Chicken-Bones** [comment] 2018-07-10 09:04
It's somewhat unintuitive, but it seems to work. Setting a flag in `ConsumeItem` should be fine.

**Comment by Jofairden** [comment] 2018-10-01 06:35
As stated, it is somewhat unintuitive but it works for this scenario. I will go ahead and close this issue since the proposed solution seeems adequate.

**Closed by Jofairden** 2018-10-01 06:35 UTC
