### ISSUE TITLE
Terraria crashes upon finding mods and i cant fix it no matter what i try

### ISSUE THREAD

**Issue by Mioloid** [blushiemagic/tModLoader#504] opened 2019-04-03 15:04 UTC
when I load up the game as soon as i get to finding mods it crashes. I don't know why this started happening because before this i would be able to reach finding recipes before it crashed

1.  Load up Terraria
2.  Get to finding mods
3. Crash with no crash log left behind

Every time i load it up this happens, I have tried deleting and reinstalling Terraria multiple times to no avail.

 tModLoader version 0.10.1.5 I have also tried 0.10.1.4 and 0.10.1.3

Mods:Thorium
MaxStackPlus
Furniture, Food and Fun
Calamity
Project_Logic
Fargo's Mutant Mod
Fargo's Souls Mod
Wing Slot
Shadows of Abaddon (SacredTools) - Closed Beta
Which Mod Is This From?
More Accessories+
Spirit Mod
Elemental Unleash
Boss Checklist
Yet Another Boss Health Bar
Joost Mod
Magic Storage
Chad's Furniture & More
Recipe Browser
Luiafk Mod
Auto Trash
WeaponOut
Vipix' Toolbox
BuilderPlus
Solutions
Friendly NPCs Don't Die
Ultraconyx
Mechtransfer
Builder's Toolbox
Silk Touch
Critter Craze
Better Paint
ModHelpers
Legendaries+
Extensible Inventory
Spectral Aves' Calamity Chiptune Boxes
Invisible Blocks & Platforms
Invisible Dye
Veinminer
World Expansion
Better Night Sky
Music Maker
Prefixes for Enemies
Boss Highlights
The Unchained Terrarian
Enigma
Ammobox+
Split
Antiaris
Thaumaturgy
Pinkymod
Beyond the Forgotten Ages
Gambler NPC
Expeditions
Expeditions Content Pack
Expeditions Addon: Interactions
The Luggage
Peculiarity
More Dialogue
The Bird Mod
Arrival of the Blind Forest
Universal Crafter
Apotheosis and Friends
AFK's Pets and More
Touhou mod
Terraria3D + Terrariahooks (off and on)
Qwerty's Bosses and Items
Mod of Redemption
AlchemistNPC Lite
Chromakey Wall
Gadget Galore
Various Weathers
Imk sushi's mod 
Imk sushi's old recipes enabler

the issue might be to do with amount of mods but i cant disable them because i can only enter my mod list once i get past loading all my mods. I also looked at someone else who had the same issue but holding left shift gave me no results

**Comment by Jofairden** [comment] 2019-04-03 16:03
When you go into the logs folder there is no client.log file ?
(Or any other kind of log file, even .txt files?)
There is no error popup?

Then I'll put my standard text: Have you tried verifying integrity of game files (steam) and reinstalling tmodloader? Have you tried removing the enabled.json file from the mods folder and reloading mods following [these](https://cdn.discordapp.com/attachments/466247288331829249/481464717043564554/Untitled_Diagram1.png) steps?

**Comment by Chicken-Bones** [comment] 2019-04-03 23:37
Also try the beta on our discord, it gives better logs

**Comment by Mioloid** [comment] 2019-04-04 14:52
I used to get a crash log when i crashed on finding recipes but now it crashes on finding mods and verifying integrity doesnt help. Also I just want to make sure i download the right beta, do you mean the newest one or just any of them?

**Comment by Chicken-Bones** [comment] 2019-04-04 14:56
Come ping either jopojelly or I on Discord, we can give you more interactive help there

**Comment by Jofairden** [comment] 2019-04-20 11:29
If you still need an invite link to the discord, this should work: https://tmodloader.net/discord

**Comment by Jofairden** [comment] 2019-04-27 16:13
Sounds like a mod issue to me. Closing because of no follow up.
To anyone having the same problem, following [these steps](https://cdn.discordapp.com/attachments/466247288331829249/481464717043564554/Untitled_Diagram1.png) can usually have you figure out the root cause of your load issue. Remember that you can hold LSHIFT during boot to skip loading mods.

**Closed by Jofairden** 2019-04-27 16:13 UTC
