### ISSUE TITLE
Beta crash when using texture pack on macOS

### ISSUE THREAD

**Issue by TheOnlyMrCat** [blushiemagic/tModLoader#527] opened 2019-04-24 03:00 UTC
### Description

Launching Terraria with a texture pack fails on Mac

### Steps to Reproduce

Have a texture pack zip file in ~/Library/Application Support/Terraria/ModLoader/TexturePacks.
On the application's launch, the game gets focus, but no window is displayed, and the game crashes.

### Versions

Tested with tModLoader Mac v0.11.Beta.3

### Additional Information

client.log shows Ionic.Zip failing to load the zip file.
```
[12:50:29] [1/INFO] [tML]: Starting tModLoader v0.11 Beta 3ms client
[12:50:29] [1/INFO] [tML]: Running on Mono 4.6.1
[12:50:29] [1/INFO] [tML]: Executable: /Volumes/Games/Steam/steamapps/common/Terraria/Terraria.app/Contents/MacOS/Terraria.exe
[12:50:29] [1/INFO] [tML]: Working Directory: /Volumes/Games/Steam/steamapps/common/Terraria/Terraria.app/Contents/MacOS
[12:50:29] [1/INFO] [tML]: Launch Parameters: 
[12:50:30] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[12:50:30] [1/DEBUG] [tML]: Assembly Resolve: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[12:50:30] [1/DEBUG] [tML]: Assembly Resolve: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[12:50:31] [1/FATAL] [Terraria]: Main engine crash
Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x01000000) at position  0x00000000
  at Ionic.Zip.ZipEntry.ReadHeader (Ionic.Zip.ZipEntry ze, System.Text.Encoding defaultEncoding) [0x00072] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
  at Ionic.Zip.ZipEntry.ReadEntry (Ionic.Zip.ZipContainer zc, System.Boolean first) [0x00044] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
  at Ionic.Zip.ZipFile.ReadIntoInstance_Orig (Ionic.Zip.ZipFile zf) [0x00086] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
  at Ionic.Zip.ZipFile.ReadIntoInstance (Ionic.Zip.ZipFile zf) [0x00154] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
   --- End of inner exception stack trace ---
  at Ionic.Zip.ZipFile.ReadIntoInstance (Ionic.Zip.ZipFile zf) [0x0018c] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
  at Ionic.Zip.ZipFile.Read (System.IO.Stream zipStream, System.IO.TextWriter statusMessageWriter, System.Text.Encoding encoding, System.EventHandler`1[TEventArgs] readProgress) [0x00074] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
  at Ionic.Zip.ZipFile.Read (System.IO.Stream zipStream) [0x00000] in <510a9a0a2eb84c1caa23d4acd845fea7>:0 
  at Terraria.TexturePackSupport.FindTexturePacks () [0x00066] in <46412489114b4ecb8593c91f228663dc>:0 
  at Terraria.Main.LoadContent () [0x0006b] in <46412489114b4ecb8593c91f228663dc>:0 
  at Microsoft.Xna.Framework.Game.Initialize () [0x00053] in <bc6b38abaaf04135afbd0534ec7f6b92>:0 
  at Terraria.Main.ClientInitialize () [0x00084] in <46412489114b4ecb8593c91f228663dc>:0 
  at Terraria.Main.Initialize () [0x064fb] in <46412489114b4ecb8593c91f228663dc>:0 
  at Microsoft.Xna.Framework.Game.DoInitialize () [0x0000d] in <bc6b38abaaf04135afbd0534ec7f6b92>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x0000e] in <bc6b38abaaf04135afbd0534ec7f6b92>:0 
  at Terraria.Program.LaunchGame_ () [0x00095] in <46412489114b4ecb8593c91f228663dc>:0 
```

**Comment by talchas** [comment] 2019-04-30 00:22
This also crashes on linux, beta4 with a different backtrace/exception (so it may be a different bug):
```
./Terraria 
[17:18:24] [1/INFO] [tML]: Starting tModLoader v0.11 Beta 4ls client
[17:18:24] [1/INFO] [tML]: Running on Mono 4.6.1
[17:18:24] [1/INFO] [tML]: Executable: /home/ben/.local/share/Steam/SteamApps/common/Terraria/tModLoader.exe
[17:18:24] [1/INFO] [tML]: Working Directory: /home/ben/.local/share/Steam/SteamApps/common/Terraria
[17:18:24] [1/INFO] [tML]: Launch Parameters: 
[17:18:24] [1/WARN] [tML]: First-chance exception reporting is not implemented on Mono
[17:18:24] [1/DEBUG] [tML]: Fallback synchronization context assigned
[17:18:25] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[17:18:25] [1/DEBUG] [tML]: Assembly Resolve: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[17:18:25] [1/DEBUG] [tML]: Assembly Resolve: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Setting breakpad minidump AppID = 105600
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197993473564 [API loaded no]
IGLDevice: OpenGLDevice
OpenGL Device: GeForce GTX 960M/PCIe/SSE2
OpenGL Driver: 4.6.0 NVIDIA 418.43
OpenGL Vendor: NVIDIA Corporation
MojoShader Profile: glsl120
Using EXT_swap_control_tear VSync!
Using EXT_swap_control_tear VSync!
Using EXT_swap_control_tear VSync!
Resolution changed to: 800x600.
[17:18:26] [1/FATAL] [Terraria]: Main engine crash
Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Ionic.Zip.SharedUtilities.StringFromBuffer (Byte[] buf, Encoding encoding) [0x00000] in data-0x14fde60 
  at Ionic.Zip.ZipEntry.ReadDirEntry (ZipFile zf, Dictionary[TKey,TValue] previouslySeen) [0x0048d] in data-0x14fde60 
  at Ionic.Zip.ZipFile.ReadCentralDirectory (ZipFile zf) [0x0005f] in data-0x14fde60 
  at Ionic.Zip.ZipFile.ReadIntoInstance (ZipFile zf) [0x00142] in data-0x14fde60 
   --- End of inner exception stack trace ---
  at Ionic.Zip.ZipFile.ReadIntoInstance (ZipFile zf) [0x0018c] in data-0x14fde60 
  at Ionic.Zip.ZipFile.Read (Stream zipStream, TextWriter statusMessageWriter, Encoding encoding, EventHandler[TEventArgs] readProgress) [0x00074] in data-0x14fde60 
  at Ionic.Zip.ZipFile.Read (Stream zipStream) [0x00000] in data-0x14fde60 
  at Terraria.TexturePackSupport.FindTexturePacks () [0x00062] in tModLoader.exe 
  at Terraria.Main.LoadContent () [0x0006b] in tModLoader.exe 
  at Microsoft.Xna.Framework.Game.Initialize () [0x00053] in FNA.dll 
  at Terraria.Main.ClientInitialize () [0x00082] in tModLoader.exe 
  at Terraria.Main.Initialize () [0x064b2] in tModLoader.exe 
  at Microsoft.Xna.Framework.Game.DoInitialize () [0x0000d] in FNA.dll 
  at Microsoft.Xna.Framework.Game.Run () [0x0000e] in FNA.dll 
  at Terraria.Program.LaunchGame_ () [0x0007c] in tModLoader.exe 
```

This occurs even with a fairly trivial zip file with just an empty "Images" folder, but does not fail with an entirely empty zip file (and fails earlier with a different message for an invalid file, so you're not somehow passing null with the completely obvious code in the patch - it sure looks like a bug in the version of Ionic.Zip being referenced or something).

**Comment by Chicken-Bones** [comment] 2019-06-02 12:59
Duplicate of #213, but also fixed

**Closed by Chicken-Bones** 2019-06-02 12:59 UTC
Labels: Vanilla Bug
