### ISSUE TITLE
,"hash or mismatch file has been modified or corrupted?" Help.

### ISSUE THREAD

**Issue by zeakchi** [blushiemagic/tModLoader#316] opened 2018-03-12 02:59 UTC
### Description

Yesterday, I updated to tModLoader v0.10.1.3 and got the update, I tested multiplayer with my friend, then a few hours later, I got this:  
Hash mismatch, data blob has been modified or corrupted
at Terraria.ModLoader.IO.TmodFile.Read(LoadedState desiredState, ReadStreamingAsset streamingHandler)
at Terraria.ModLoader.ModLoader.FindMods()

Whats going on? I checked the Tmod loader discord and supposedly, the latest version fixed this problem but I still got the problem that was supposedly fixed. I must of redownloaded TmodLoader at least 10 times...

### Steps to Reproduce

1. Redownload TmodLoader
2. Extract with Winrar
3. Replace Terraria Files with TmodLoader Files in their destination.
4. Launch Game and Enjoy.
### Expected behavior 

Everything works properly and enjoy the game.

### Actual behavior

I get the same message shown above making me non-accessible to my mods in-game.

### Reproduction frequency

Every, Single, Time I redo the process.

### Version

TmodLoader v0.10.1.3

### Mods

1. Calamity Mod v1.2.3.8: on
2. Fargos Mutant Mod: on
3. Shorter Respawn Time: on
4. AlchemistNPC: on
5. HEROs Mod: off
6. Another Boss Healthbar: on
7. Joost Mod v0.6.4: on
8. Auto Trash: on
9. Crystilium v11.3.1.5: on
10. Recipe browser v0.6: on
11. Spirit mod v1.3.3.1: on
12. Tremor Mod Remastered v1.3.2.7: on
13. Thorium mod v1.4.3.8: on
14. Boss checklist v0.1.5.2: on
15. Yet another boss health bar 1.2.1: on

(Oh yeah, I cant change the off/on Because I can't access my mods folder In-game or else i'll get the above...)
### Additional Information

This just happened when I Installed the latest version of TmodLoader. This never happened when I started with the old version v0.10.1.1 til I updated to the new TmodLoader v0.10.1.3. Please Help, and thanks.

**Comment by Jofairden** [comment] 2018-03-12 12:40
Duplicate of #315

**Closed by Jofairden** 2018-03-12 12:40 UTC

**Comment by zeakchi** [comment] 2018-03-13 01:27
oh, i didn't that, thanks
