### ISSUE TITLE
Update All tried to download all the mods

### ISSUE THREAD

**Issue by zauberparacelsus** [blushiemagic/tModLoader#542] opened 2019-05-10 11:50 UTC
### Description
Clicking `Update All` in the mod browser caused it to download "updates" for a dozen mods I hadn't had installed, then aborted when a bandwidth limit was hit.

### Steps to Reproduce
Beyond clicking "Update All", I do not have a repro for this bug, and it could be random.

### Expected behavior 
It should just download the mods I had installed

### Actual behavior
It tried to download a bunch of mods I didn't install.

### Reproduction frequency
It has only happened once so far.

### Versions
v0.10.1.5 tModLoader

### Mods
Copy of my enabled.json file:
```
[
  "chadsfurni",
  "AutoTrash",
  "BossChecklist",
  "HEROsMod",
  "Infinity",
  "MagicStorage",
  "MoreAccessories",
  "VendingMachines",
  "WingSlot",
  "Wireless",
  "WMITF",
  "SpiritMod",
  "MultiLure",
  "Fishing3",
  "MoreChestLoot",
  "ShorterRespawn",
  "MinionCrits",
  "CalamityAddon",
  "InstantRespawn",
  "WorldGenPreviewer",
  "EnemyAccessories",
  "FishingRewardRecipes",
  "BuilderPlus",
  "ThoriumMod",
  "VeinMiner",
  "TheOneLibrary",
  "MoreBiomeFishingCrates",
  "NoFishTimer",
  "NoMoreTombs",
  "StopDying",
  "AnglerQuestAnnouncement",
  "fairsouldrops",
  "MaxStackPlus",
  "DNIWpnUpgr",
  "ReducedGrinding",
  "YoyoAttackSpeedWorkaround",
  "HamstarHelpers",
  "Redemption",
  "ItemMagnetPlus",
  "TerrariaHooks",
  "FlyingMinionsIgnoreTerrain",
  "BannerBonanza",
  "pinkymod",
  "MonsterExpert",
  "Antisocial",
  "CalamityMod",
  "FargowiltasSouls",
  "Fargowiltas",
  "CheatSheet",
  "ReforgeArmor",
  "SummonersAssociation",
  "WerewolfMod",
  "FishingCrateAdditions",
  "LootBags",
  "imkSushisMod",
  "imkSushisModOldRecipesEnabler",
  "MinibossExpansion",
  "BossAssist",
  "AssortedCrazyThings",
  "AlchemistNPCLite",
  "niceblocks",
  "CosmeticVariety",
  "LearnByDoing",
  "RPG",
  "ShopExpander",
  "MeteorPickaxe",
  "Loot"
]
```

**Comment by wooden-utensil** [comment] 2019-05-10 11:52
_Hmm_? Try going to show all mods need updating filter, and clicking update for each mod, _one by one_?

**Comment by zauberparacelsus** [comment] 2019-05-10 11:53
@wooden-utensil Already did that.

**Comment by wooden-utensil** [comment] 2019-05-10 11:55
@zauberparacelsus 

So all the mods, even ones you don't have appeared in that filtered list?

**Comment by zauberparacelsus** [comment] 2019-05-10 13:04
No.  When this happened, I had already filtered it to just show the mods that had updates, four in total.  When I clicked Update All, it started downloading at least a dozen different mods other than what I was trying to update.  Then I got a warning about the mod browser having exhausted its bandwidth limit.  After that, I tried to manually download the updated mods individually, and they downloaded without issue.

**Comment by wooden-utensil** [comment] 2019-05-10 13:17
Hmm. The mod browser must be searching through all the mods (the online ones) and downloading them if they match the filter: _"has been installed and has updates available"_. Someone must have the filter wrong and match all mods, even ones that don't match the filter: _"has been installed and has updates available"_? Try contacting one of the contributors and see if they can help.

**Comment by JavidPack** [comment] 2019-05-11 01:58
@zauberparacelsus I can't replicate on 0.10.1.5, or on 0.11, so I don't think the issue exists anymore.

@wooden-utensil This is a bug reporting place. You don't need to tell people to contact one of the contributors for help, that's precisely what this place is for already.

I'm gonna close this unless it can be replicated on 0.11 since all the logic has been changed already anyway.

**Closed by JavidPack** 2019-05-11 01:58 UTC

**Comment by Jofairden** [comment] 2019-05-11 09:24
@wooden-utensil Genuine question, do you know the tML code? You're making a bunch of guesses as to what happens, _but have you actually looked at the code?_ It can be confusing when you ask for more details but aren't the one to fix the code.

**Comment by wooden-utensil** [comment] 2019-05-12 02:22
@Jofairden Well, it's just a guess. I'll try to look into the code, and see the cause. That's just my guess though.
