### ISSUE TITLE
Vanilla Lamp Posts Drawing Incorrectly

### ISSUE THREAD

**Issue by strongrex2001** [blushiemagic/tModLoader#424] opened 2018-10-05 01:08 UTC
### Description
Vanilla lamp posts are drawing incorrectly.

### Steps to Reproduce
1. Switch all mods off
2. Enter a world and put a `ID:342` (Tiki Torch) on the floor

### Expected behavior 
I don't have got screenshots correct behaviors now! (๑•ᴗ•๑)

### Actual behavior
![ScreenShot](http://bmob-cdn-8711.b0.upaiyun.com/2018/10/05/3bce0798408571d680eca878730c8dbf.png)

### Reproduction frequency
Seemingly 100%.

### Versions
v0.10.0.5 tModLoader

### Mods
None

**Comment by JavidPack** [comment] 2018-10-05 06:36
It seems to work fine for others. Can you test again and this time make sure no mods are loaded at all in the same game session? Sometimes mods have bugs and don't unload all of their changes properly, so if you had mods enabled and then disabled them in the same game session, it's not guaranteed that the effect of those mods is completely undone.

I'm guessing the issue is a Mod you had enabled but disabled to test this issue. 

If you enable mods 1 by 1 until it happens again after starting with 0, you should be able to find the mod.

**Comment by Jofairden** [comment] 2018-10-06 13:10
I just went in game and placed a tiki torch, and it worked fine for me. We had several people in our chat try it as well, and it worked fine for them too. It's definitely an error on our end.

**Comment by strongrex2001** [comment] 2018-10-07 08:56
I observed in detail and found that the tiki torch isn't really 'placed'. Once it is put on to the floor, it immediately (not even waiting for a frame) acted as if it is picked and drops on to the ground, leaving only a light as the screenshot shows.
I found that with all mods off, and put a tiki torch again, it's working properly. With Example Mod on, it's still working properly. With my mod on, it's not.
I only know that it happens before `GlobalTile.PlaceInWorld`. And `ID:341` Lamppost works fine.

**Comment by strongrex2001** [comment] 2018-10-12 10:55
Sorry for the inconvenience caused by my misjudging. I'm heading for the discord. Thank you!

**Comment by strongrex2001** [comment] 2018-10-13 00:55
Hi! I managed to reproduce the problem.
```csharp
using Terraria;
using Terraria.ModLoader;
using Terraria.ObjectData;
using Terraria.DataStructures;
using Terraria.Enums;
using Microsoft.Xna.Framework;
using System.Windows.Forms;

namespace BugReproducer {
    public class BugReproducer : Mod {
        public BugReproducer() {
			Properties = new ModProperties() {
				Autoload = true,
				AutoloadGores = true,
				AutoloadSounds = true,
				AutoloadBackgrounds = true
			};
		}
    }

    public class TestTTile : ModTile {
        public override void SetDefaults() {
            ModTranslation name = CreateMapEntryName();
            name.SetDefault("TestTile");
            MessageBox.Show(Main.tileAlch[93].ToString());  // False
            MessageBox.Show(Type.ToString());  // 472

            Main.tileAlch[Type] = true;
            Main.tileLighted[Type] = true;
            Main.tileFrameImportant[Type] = true;
            Main.tileSolid[Type] = false;

            TileObjectData.newTile.CoordinateHeights = new int[]
            {
                16,
                16,
                16
            };
            TileObjectData.newTile.Origin = new Point16(1, 1);
            TileObjectData.newTile.CopyFrom(TileObjectData.Style1xX);
            TileObjectData.newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop, TileObjectData.newTile.Width, 0);
            TileObjectData.newTile.UsesCustomCanPlace = true;
            TileObjectData.newTile.CoordinateWidth = 16;
            TileObjectData.newTile.CoordinatePadding = 0;
            TileObjectData.addTile(Type);

            AddMapEntry(new Color(200, 200, 200), name);
        }
    }
}
```
Since `Type` is 472, nothing should be changed about `Lamps`..

**Comment by strongrex2001** [comment] 2018-10-13 00:56
No existence of the `TestTTile` is needed. Even if you Load and immediately Unload the mod, the problem already occurs.

**Comment by JavidPack** [comment] 2018-10-13 05:45
Looks like Main.tileAlch[Type] = true; is the issue, delete that.

Also note that anything editing TileObjectData.newTile before TileObjectData.newTile.CopyFrom(TileObjectData.Style1xX); is ignored since CopyFrom resets it.

Also, Style1xX already has most of those items already set, so you can delete them. Only CoordinatePadding = 0; is unique I think.

**Comment by strongrex2001** [comment] 2018-10-13 11:31
But why does it affect the vanilla tiki torch?

**Comment by JavidPack** [comment] 2018-10-13 20:44
I did not notice anything wrong with TikiTorch when I used your code, only TestTile was buggy. 

In the past, things like incorrect order of TileObjectData.addTile(Type); and other things have caused similar bugs. I suggest checking your other tiles and making sure addTile is at the end and CopyFrom is at the beginning.

**Comment by strongrex2001** [comment] 2018-10-14 02:02
I'm only enabling this BugReproducer..

**Comment by Jofairden** [comment] 2018-10-14 10:48
Just a reminder that you are on a very old version, you should update to v0.10.1.5 of tModLoader

**Comment by JavidPack** [comment] 2018-11-17 00:57
I think we'll close this for now. I tested it and it worked. I'm not sure if your version was old, but if so, when you test this again, make sure you are on the very latest tmodloader, then post the full source and compiled .tmod here and we can reopen this issue.

**Closed by JavidPack** 2018-11-17 00:57 UTC
