### ISSUE TITLE
It's difficult to find mods on the browser

### ISSUE THREAD

**Issue by Tiktalik** [blushiemagic/tModLoader#252] opened 2017-09-26 19:37 UTC
### Description

The mod browser, in its current state, is nigh-unusable as a tool for the discovery of new mods. There's no categorization, and the browser is full of barely-developed mods without so much as a description added.

### Suggested Fix

First of all, categories for mods would be nice. Megamod (like Spirit, Tremor, Calamity, Thorium), Utility (Recipe Browser, Simplified Startup), Weaponry, Biomes, or balance (Reduced Grinding) would be useful, and allow you to separate content-adding mods and other types. 

Also, while that'd probably require lot of effort, the change I'd most like to see probably wouldn't.

Going forward, I think mods should require a description of at least 140 characters in order to be accepted and displayed on the mod browser.  It wouldn't take more than a minute to write a description, and it'd neatly solve the issue of vaguely named mods with "Modname is a pretty cool mod, it does...this. Modify this file with a description of your mod" in their description cluttering the browser.

**Comment by Jofairden** [comment] 2017-09-29 10:39
I don't think requirements for descriptions to be accepted is nice or needed in any way. Ultimately it's their mod, if they don't add a good description they likely miss out on a lot of people, and that's their problem not anyone else's (they can put as much effort as they want into selling their mod to visitors, or as little as they want. their choice)

**Comment by Blazingfireflies** [comment] 2017-10-05 02:29
maybe if no description is added then the mod doesn't have the text saying "Modname is a pretty cool mod, it does...this. Modify this file with a description of your mod"

and there should be a way to determine if a mod is barely developed or actually impressive. the things that you can hover over to see the items on the side is cool, but a little extra feels needed

**Comment by Chicken-Bones** [comment] 2017-10-05 04:24
I agree with the original statement, but discovery of new mods is a fundamentally difficult problem. I think the first step is to distinguish authors seeking discovery (ones who have at least a polished functioning v1 of their mod) from those who just threw it up there while it's still in development. 

I propose a discovery section, for mods below a certain popularity threshold, requiring a description of certain length, and a link (forum or otherwise). This section could later be embellished with a simple star rating system.

I also agree with the suggestion of categories in the mod browser.

All this is dependent on the availability of priority dev time, especially since some things will need to be implemented on jopo's end

**Comment by Jofairden** [comment] 2017-10-05 08:46
Well, I still beg to differ. Ultimately it is a non-issue, because in the end you decide if you judge a mod by its description and in the end the modder decides to provide a good description or not. A solution for the default `"Modname is a pretty cool mod, it does...this. Modify this file with a description of your mod"` description would be to remove it from the mod generator. In case you didn't know, it comes from a generator and isn't added by the browser if there is no description. 

Applying certain restrictions to a service tends to become an annoying trend and do more harm rather than good, unless highly necessary I will always be against this. Categories are most likely coming at some point, maybe even rating (no guarantees) and possibly trending/non-trending sections. But again, most if not all of these features require good effort to implement.. so it will boil down to a set of features all developers agree with and someone having enough time to make them. (which I or CB certainly do not at the moment..)

**Comment by Jofairden** [comment] 2017-12-06 19:07
Duplicate of #245

**Closed by Jofairden** 2017-12-06 19:07 UTC
Labels: Duplicate, Suggestion/Feedback
