### ISSUE TITLE
Offer 64bit versions of tModLoader

### ISSUE THREAD

**Issue by bloodyshade** [blushiemagic/tModLoader#256] opened 2017-10-11 12:32 UTC
More of a suggestion than an issue, but would it be possible for you guys to offer compiled 64bit versions of tModLoader?

The reasoning being mostly that people using several big mods (I, for instance, have all big content mods and several others installed) might run into OutOfMemory errors due to the limited 2GB for 32bit executables, in fact even setting the LAA flag in the PE header to allow for 4GBs still isn't enough sometimes (I run into it less often now, but it still happens).

This might be how resources are handled within terraria or maybe improper cleanup by the mods, but having a 64bit version would at least mitigate the limiting nature (memory wise) of the 32bit one.

**Comment by Jofairden** [comment] 2017-10-11 13:10
It's not possible,  we would've offered it otherwise.  tModLoader  is already patched by default so you should have more than 2GB available. Up to 3.5Gb or so

**Comment by bloodyshade** [comment] 2017-10-11 21:19
Just to clear it up, is that because of the reference dependencies, which are 32bit? (ReLogic)

**Comment by Jofairden** [comment] 2017-10-11 21:28
Well, it's a void. One of our best persons failed multiple times trying make Terraria 64 bit.
You basically need to rebuild XNA Game to 64bit which seems impossible,

**Comment by bloodyshade** [comment] 2017-10-11 22:02
Ah I see, the problem then is that there is no 64bit support for XNA itself. That is a bummer, guess the best that can be done is try to optimize how mods/resources are managed to avoid them using gbs of ram unnecessarily. Thanks for the info.

**Comment by PoroCYon** [comment] 2017-10-12 18:38
It could be possible to recompile it (or hack around `AppDomain.ResolveAssembly`) to work with FNA instead (as it works on Windows, too), but then other problems arise: (Disclaimer: I'm not willing to do these things.)

* Some content files can only be read by XNA, not FNA.
  * This can be mitigated by using the Linux (or OS X) content files.
* `ReLogic.dll` is 32-bit, so it will fail to work.
  * This is (partially) because it references XNA, so just recompile that as well.
  * It also uses `ReLogic.Native.dll`, which is, as the name implies, a *native* assembly, so just recompiling it won't work. It could be reimplemented, though, because it's not that large and relatively easy to reverse-engineer.
  * Another option is to use the Linux version of the DLL here, as well, but beware when it tries to do Linux-specific stuff.

Maybe ReLogic (i.e. Yoraiz0r, probably, poor him...) could be pressured to do it, as it'd be much easier for them. (If they complain about FNA being slower than XNA[0], point out all the bloat in their code.)

Or, yunooöh, just switch to an OS that doesn't suck `:P` (*ahem* GNU/Linux *ahem*).

[0]: FNA is pure C#, while XNA is written in C++/CLI, thus having a more direct form of native calls (much faster than P/Invokes).

**Comment by Jofairden** [comment] 2017-10-12 19:54
I'm pretty sure Yorai said it will not be happening to good luck pressuring him, he will only ignore you more and more.

**Comment by PoroCYon** [comment] 2017-10-12 20:05
That's ~~fair enough~~ more than just 'fair enough'.

**Comment by zauberparacelsus** [comment] 2017-10-12 20:36
@PoroCYon Problem with Linux, is that playing Terraria means you're running it through Mono, instead of the .Net framework.  I've seen the following issues when doing so:

- Reduced framerates, resulting from the aforementioned P/Invoke overhead in FNA, along with the fact that [mono is just plain slow](http://tirania.org/blog/archive/2014/Jul-23.html).
- With a lot of mods installed, the game can take 5-10 minutes to load.
- Higher memory usage
- More memory leaks (or garbage collection flaws in Mono)
- More out-of-memory crashes
- When getting close to an out-of-memory crash, game saving no longer works, and may actually trigger the crash.
- When an out-of-memory crash occurs, some savefile corruption occurs (I forget the exact details, it's been a while because I don't play modded Terraria on Linux anymore)

I dual-boot with Windows and Linux, each running on a separate SSD.  I have Terraria installed on both.  And although I prefer Linux, I only play modded Terraria on Windows because otherwise I have too many headaches.

**Comment by PoroCYon** [comment] 2017-10-12 22:24
* Mono now has an LLVM backend. Furthermore, my laptop isn't the most performant (it's 6 years old), and yet Terraria (read: Prism) runs at an acceptable framerate. A significant amount of the lag is probably caused by Terraria itself, though.
* That could be caused by many factors, such as syscalls, disk access, assembly loading (and resolving!), etc.
* Not for me... ¯\_(ツ)_/¯ (maybe because I don't use tModLoader)
* Not for me. Then again, Terraria's shitty coding is a thing. (Implicit instance keepalive is possible, even thoug there's a GC.)
* None here. You are running a 64-bit kernel etc., right?

I only run Linux (Parabola GNU/Linux-libre-hardened).

I have to admit: I modified FNA [slightly](https://github.com/TerrariaPrismTeam/Prism/blob/develop/References/FNA.patch.readme.txt) (see also [this](https://github.com/TerrariaPrismTeam/Prism/blob/develop/References/FNA.patch) ), so this could have some consequences.

**Comment by zauberparacelsus** [comment] 2017-10-13 00:58
Yeah, I am running a 64-bit kernel.  As for the slow loading, I think it may be due to PNG loading overhead, since it seems to spend most of its time on PNG loading.  PNG is probably the slowest compressed image format out there, and any overhead in Mono probably makes it worse.  PNG is also unusual for a compressed file format, in that the compression and decompression times are roughly equal.  With most compressed formats, the decompression time is much less than the compression time.

**Comment by Jofairden** [comment] 2017-11-20 16:23
Closed for now to prevent polluting the issue list. Can be opened again at any time if needed. Again, 64 bit was attempted with no succession, do not expect anything.

**Closed by Jofairden** 2017-11-20 16:23 UTC
Labels: Discussion

**Comment by gothicserpent** [comment] 2020-11-29 00:42
I just have to say I tried base tmodloader several times and kept running into crashes using the system. I had several mods loaded and when I experienced the crashes, I sometimes lost save data, but was always very disappointed, especially when in any other respect the system works really well. 

Soon as I switched to this https://github.com/Dradonhunter11/tModLoader64bit/releases it worked great. Really contributed to making the game fun for me to play, and probably many others extending the lifetime of the repo and value long term. 4 GB  is not enough RAM with modern standards.

**Please** add 64 bit support natively to get over the 4GB memory limit.
