### ISSUE TITLE
Support for c#7 compilation

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#324] opened 2018-03-28 07:03 UTC
We should add support using the compiler for c#7 as this version introduces a variety of benefits for modders.

## Benefits
Most notably:

1. Out variables (`out var`)
2. Pattern matching (`x is y`) [very strong with switch-case statements]
3. Tuple types and literals. _Named tuples:_ `(var my, var named, var tuple) x` -> `x.my` `x.named` `x.tuple`
4. Local scope functions (nested functions) [YEEESSSSS]

More information: https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/

Assigning @Chicken-Bones

**Comment by Chicken-Bones** [comment] 2018-09-04 08:50
https://github.com/blushiemagic/tModLoader/commit/276b575ac5c875bb13ad47ef2a4b1562155b03dd

**Comment by Chicken-Bones** [comment] 2018-09-04 09:08
I have only confirmed that mods /compile/ with new language features. They may not actually work due to framework incompatiblities. For now, compile your mods targeting .NET 4.0 client profile and report any unwanted dependencies on this issue

**Comment by Chicken-Bones** [comment] 2018-09-17 03:05
Need to change RoslynWrapper to find and target the .NET 4.0 Client profile rather than just what is currently referenced.

**Comment by Chicken-Bones** [comment] 2018-11-17 14:42
Technically fixed as of fc7d56ed7518dc295b59cafe9d61607cda78ad0a
TODO:
Create separate auto-download for ModCompile folder. 
Create "Enable Developer Mode" button that replaces "Mod Sources" until activated
Download the "v4.0 Client Reference Assemblies" inside the ModCompile folder after prompting, if the user has not installed VS

**Closed** 2018-11-22 03:11 UTC

**Comment by Chicken-Bones** [comment] 2019-01-16 03:02
For anyone following this
https://github.com/blushiemagic/tModLoader/commit/226dff69773915d19e898ac1c7ce2d345abbabed
